INSERT INTO amenidades (id, nombre) VALUES
(1, 'Cocina equipada (con electrodomésticos modernos)'),
(2, 'Aire acondicionado'),
(3, 'Calefacción'),
(4, 'Wi-Fi gratuito'),
(5, 'Televisión por cable o satélite'),
(6, 'Lavadora y secadora'),
(7, 'Piscina'),
(8, 'Jardín o patio'),
(9, 'Barbacoa o parrilla'),
(10, 'Terraza o balcón'),
(11, 'Gimnasio en casa'),
(12, 'Garaje o espacio de estacionamiento'),
(13, 'Sistema de seguridad'),
(14, 'Habitaciones con baño en suite'),
(15, 'Muebles de exterior'),
(16, 'Microondas'),
(17, 'Lavavajillas'),
(18, 'Cafetera'),
(19, 'Ropa de cama y toallas incluidas'),
(20, 'Acceso a áreas comunes (piscina, gimnasio)'),
(21, 'Camas adicionales o sofá cama'),
(22, 'Servicios de limpieza opcionales'),
(23, 'Acceso a transporte público cercano'),
(24, 'Mascotas permitidas'),
(25, 'Cercanía a tiendas y restaurantes'),
(26, 'Sistema de calefacción por suelo radiante'),
(27, 'Escritorio o área de trabajo'),
(28, 'Sistemas de entretenimiento (videojuegos, equipo de música)'),
(29, 'Chimenea'),
(30, 'Acceso a internet de alta velocidad');