"""Migración Inicial

Revision ID: b8c87bf5c90c
Revises: 
Create Date: 2026-01-24 17:41:19.844597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c87bf5c90c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('preguntas_recuperacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('texto')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_casa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('imagen_perfil', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('contrasena', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('domicilio', sa.String(length=255), nullable=False),
    sa.Column('pregunta_recuperacion_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_recuperacion', sa.String(length=255), nullable=False),
    sa.Column('permitir_huella', sa.Integer(), nullable=False),
    sa.Column('token_publico', sa.String(length=255), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('estado_cuenta', sa.String(length=20), nullable=False),
    sa.Column('nombre_titular', sa.String(length=120), nullable=False),
    sa.Column('numero_encriptado', sa.String(length=255), nullable=False),
    sa.Column('fecha_expiracion', sa.String(length=7), nullable=False),
    sa.Column('marca', sa.String(length=20), nullable=False),
    sa.Column('ultimos_4', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_recuperacion_id'], ['preguntas_recuperacion.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('propiedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_casa_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('titulo_publicacion', sa.String(length=150), nullable=False),
    sa.Column('descripcion_publicacion', sa.Text(), nullable=True),
    sa.Column('precio_noche', sa.Float(), nullable=False),
    sa.Column('huespedes', sa.Integer(), nullable=False),
    sa.Column('habitaciones', sa.Integer(), nullable=False),
    sa.Column('camas', sa.Integer(), nullable=False),
    sa.Column('banos', sa.Integer(), nullable=False),
    sa.Column('cocina', sa.Boolean(), nullable=False),
    sa.Column('reglas_uso', sa.Text(), nullable=True),
    sa.Column('vehiculos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tipo_casa_id'], ['tipos_casa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_hobbies',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'hobby_id')
    )
    op.create_table('usuario_tipos_casa',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_casa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_casa_id'], ['tipos_casa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'tipo_casa_id')
    )
    op.create_table('arrendamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('habitacion', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_propiedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('url_foto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propiedad_amenidades',
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('amenidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenidad_id'], ['amenidades.id'], ),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedad.id'], ),
    sa.PrimaryKeyConstraint('propiedad_id', 'amenidad_id')
    )
    op.create_table('propiedad_hobbies',
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedad.id'], ),
    sa.PrimaryKeyConstraint('propiedad_id', 'hobby_id')
    )
    op.create_table('estado_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado_dispositivo')
    op.drop_table('propiedad_hobbies')
    op.drop_table('propiedad_amenidades')
    op.drop_table('fotos_propiedades')
    op.drop_table('dispositivo')
    op.drop_table('arrendamientos')
    op.drop_table('usuario_tipos_casa')
    op.drop_table('usuario_hobbies')
    op.drop_table('propiedad')
    op.drop_table('usuario')
    op.drop_table('tipos_casa')
    op.drop_table('roles')
    op.drop_table('preguntas_recuperacion')
    op.drop_table('hobbies')
    op.drop_table('amenidades')
    # ### end Alembic commands ###
